---
- hosts: all
  tasks:
   - name: Download Docker installer File
     get_url: url=https://get.docker.com/ dest=/tmp/docker.sh
   - name: change permissions on File
     file: path=/tmp/docker.sh state=touch mode="a+x"
   - name: Install docker
     shell: bash +x /tmp/docker.sh
   - name: start docker daemon
     service: name=docker state=running
